# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/devcontainers/python:3.10
# Add any extra OS packages here
# RUN apt-get update && apt-get install -y --no-install-recommends <packages> && rm -rf /var/lib/apt/lists/*
